/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
export async function seed(knex) {
  await knex("exercises").del();

  //  Day 1 (Legs)
  await knex("exercises").insert([
    {
      id: 1,
      day_id: 1,
      name: "Goblet Pause Squat",
      sets: 4,
      reps: 12,
      weight: 0,
      image: "goblet-pause-squat.jpg",
      video_url: "https://example.com/goblet-pause-squat",
    },
    {
      id: 2,
      day_id: 1,
      name: "Goblet Squat",
      sets: 4,
      reps: 12,
      weight: 0,
      image: "goblet-squat.jpg",
      video_url: "https://example.com/goblet-squat",
    },
    {
      id: 3,
      day_id: 1,
      name: "Split Squat",
      sets: 4,
      reps: 12,
      weight: 0,
      image: "split-squat.jpg",
      video_url: "https://example.com/split-squat",
    },
    {
      id: 4,
      day_id: 1,
      name: "Pause Front Dumbbell Squat",
      sets: 4,
      reps: 12,
      weight: 0,
      image: "pause-front-dumbbell-squat.jpg",
      video_url: "https://example.com/pause-front-squat",
    },

    //  Day 2 (Upper Body)
    {
      id: 5,
      day_id: 2,
      name: "Bent Over Dumbbell Rows",
      sets: 4,
      reps: 12,
      weight: 0,
      image: "bent-over-dumbbell-rows.jpg",
      video_url: "https://example.com/bent-over-rows",
    },
    {
      id: 6,
      day_id: 2,
      name: "Shoulder Press",
      sets: 4,
      reps: 12,
      weight: 0,
      image: "shoulder-press.jpg",
      video_url: "https://example.com/shoulder-press",
    },
    {
      id: 7,
      day_id: 2,
      name: "Tricep Kickbacks",
      sets: 4,
      reps: 12,
      weight: 0,
      image: "tricep-kickbacks.jpg",
      video_url: "https://example.com/tricep-kickbacks",
    },
    {
      id: 8,
      day_id: 2,
      name: "Chest Flyes",
      sets: 4,
      reps: 12,
      weight: 0,
      image: "chest-flyes.jpg",
      video_url: "https://example.com/chest-flyes",
    },

    //  Day 3 (Glutes)
    {
      id: 9,
      day_id: 3,
      name: "Deadlift",
      sets: 4,
      reps: 12,
      weight: 0,
      image: "deadlift.jpg",
      video_url: "https://example.com/deadlift",
    },
    {
      id: 10,
      day_id: 3,
      name: "Hip Thrust",
      sets: 4,
      reps: 12,
      weight: 0,
      image: "hip-thrust.jpg",
      video_url: "https://example.com/hip-thrust",
    },
    {
      id: 11,
      day_id: 3,
      name: "Bulgarian Split Squat",
      sets: 4,
      reps: 12,
      weight: 0,
      image: "bulgarian-split-squat.jpg",
      video_url: "https://example.com/bulgarian-split-squat",
    },
    {
      id: 12,
      day_id: 3,
      name: "Sumo Squats",
      sets: 4,
      reps: 12,
      weight: 0,
      image: "sumo-squat.jpg",
      video_url: "https://example.com/sumo-squats",
    },

    // Inserts seed entries for Day 4 (HIIT Cardio)
    {
      id: 13,
      day_id: 4,
      name: "High Knees",
      sets: 4,
      reps: 12,
      weight: 0,
      image: "high-knees.jpg",
      video_url: "https://example.com/high-knees",
    },
    {
      id: 14,
      day_id: 4,
      name: "Rotating Planks",
      sets: 4,
      reps: 12,
      weight: 0,
      image: "rotating-planks.jpg",
      video_url: "https://example.com/rotating-planks",
    },
    {
      id: 15,
      day_id: 4,
      name: "Touchdown Pop Squat",
      sets: 4,
      reps: 12,
      weight: 0,
      image: "touchdown-pop-squat.jpg",
      video_url: "https://example.com/touchdown-pop-squat",
    },
    {
      id: 16,
      day_id: 4,
      name: "Mountain Climbers",
      sets: 4,
      reps: 12,
      weight: 0,
      image: "mountain-climbers.jpg",
      video_url: "https://example.com/mountain-climbers",
    },
    {
      id: 17,
      day_id: 4,
      name: "Lateral Jump Squats",
      sets: 4,
      reps: 12,
      weight: 0,
      image: "lateral-jump-squats.jpg",
      video_url: "https://example.com/lateral-jump-squats",
    },

    // Day 5 (Full Body)
    {
      id: 18,
      day_id: 5,
      name: "Single Arm Shoulder Press with Static Split Squat",
      sets: 4,
      reps: 12,
      weight: 0,
      image: "single-arm-shoulder-press.jpg",
      video_url: "https://example.com/single-arm-press",
    },
    {
      id: 19,
      day_id: 5,
      name: "Dumbbell Good Mornings",
      sets: 4,
      reps: 12,
      weight: 0,
      image: "dumbbell-good-mornings.jpg",
      video_url: "https://example.com/dumbbell-good-mornings",
    },
    {
      id: 20,
      day_id: 5,
      name: "Squat Bicep Curls",
      sets: 4,
      reps: 12,
      weight: 0,
      image: "squat-bicep-curls.jpg",
      video_url: "https://example.com/squat-bicep-curls",
    },
  ]);
}
