/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
export async function seed(knex) {
  await knex("exercises").del();

  //  Day 1 (Legs)
  await knex("exercises").insert([
    {
      id: 1,
      day_id: 1,
      name: "Goblet Pause Squat",
      sets: 4,
      reps: 12,
      weight: 0,
      image: "goblet-pause-squat.jpg",
      video_url: "https://www.youtube.com/embed/8jeMsehQJK0?si=37Odhhqy6TbxzavM",
    },
    {
      id: 2,
      day_id: 1,
      name: "Goblet Squat",
      sets: 4,
      reps: 12,
      weight: 0,
      image: "goblet-squat.jpg",
      video_url: "https://www.youtube.com/embed/pEGfGwp6IEA?si=VPod2jWtvqiZhkNS",
    },
    {
      id: 3,
      day_id: 1,
      name: "Split Squat",
      sets: 4,
      reps: 12,
      weight: 0,
      image: "split-squat.jpg",
      video_url: "https://www.youtube.com/embed/hXpGSa5HYqY?si=c2EHFc7Zf2EDfKQM",
    },
    {
      id: 4,
      day_id: 1,
      name: "Pause Front Dumbbell Squat",
      sets: 4,
      reps: 12,
      weight: 0,
      image: "pause-front-dumbbell-squat.jpg",
      video_url: "https://www.youtube.com/embed/7CuKlSgu1B0?si=jTUXr0T0HKGaiIVM",
    },

    //  Day 2 (Upper Body)
    {
      id: 5,
      day_id: 2,
      name: "Bent Over Dumbbell Rows",
      sets: 4,
      reps: 12,
      weight: 0,
      image: "bent-over-dumbbell-rows.jpg",
      video_url: "https://www.youtube.com/embed/6gvmcqr226U?si=x0En5oI3mHCtfk5x",
    },
    {
      id: 6,
      day_id: 2,
      name: "Shoulder Press",
      sets: 4,
      reps: 12,
      weight: 0,
      image: "shoulder-press.jpg",
      video_url: "https://www.youtube.com/embed/HzIiNhHhhtA?si=QO-xy3-sampwS5_f",
    },
    {
      id: 7,
      day_id: 2,
      name: "Tricep Kickbacks",
      sets: 4,
      reps: 12,
      weight: 0,
      image: "tricep-kickbacks.jpg",
      video_url: "https://www.youtube.com/embed/m_UlDFNX4mk?si=kR1OWoPm_M2pWLfF",
    },
    {
      id: 8,
      day_id: 2,
      name: "Chest Flyes",
      sets: 4,
      reps: 12,
      weight: 0,
      image: "chest-flyes.jpg",
      video_url: "https://www.youtube.com/embed/Nhvz9EzdJ4U?si=5z-wjfvujQCvYRVk",
    },

    //  Day 3 (Glutes)
    {
      id: 9,
      day_id: 3,
      name: "Deadlift",
      sets: 4,
      reps: 12,
      weight: 0,
      image: "deadlift.jpg",
      video_url: "https://www.youtube.com/embed/plb5jEO4Unw?si=EKBZW5SlanF3sH5Z",
    },
    {
      id: 10,
      day_id: 3,
      name: "Hip Thrust",
      sets: 4,
      reps: 12,
      weight: 0,
      image: "hip-thrust.jpg",
      video_url: "https://www.youtube.com/embed/Zp3mZV6Plyg?si=54TgNPKk3XSLH-TN",
    },
    {
      id: 11,
      day_id: 3,
      name: "Bulgarian Split Squat",
      sets: 4,
      reps: 12,
      weight: 0,
      image: "bulgarian-split-squat.jpg",
      video_url: "https://www.youtube.com/embed/vLuhN_glFZ8?si=G8OMnETOmJUtW0ey",
    },
    {
      id: 12,
      day_id: 3,
      name: "Sumo Squats",
      sets: 4,
      reps: 12,
      weight: 0,
      image: "sumo-squat.jpg",
      video_url: "https://www.youtube.com/embed/5cyIfPETLJk?si=fgLfRoYpIb7oKdBq",
    },

    // Inserts seed entries for Day 4 (HIIT Cardio)
    {
      id: 13,
      day_id: 4,
      name: "High Knees",
      sets: 4,
      reps: 12,
      weight: 0,
      image: "high-knees.jpg",
      video_url: "https://www.youtube.com/embed/sTvekaq6vOU?si=XU3Y0ELZB2tUDMdq",
    },
    {
      id: 14,
      day_id: 4,
      name: "Rotating Planks",
      sets: 4,
      reps: 12,
      weight: 0,
      image: "rotating-planks.jpg",
      video_url: "https://www.youtube.com/embed/VBd6DBVNUYg?si=gcg8oE3DsGdTsx22",
    },
    {
      id: 15,
      day_id: 4,
      name: "Touchdown Pop Squat",
      sets: 4,
      reps: 12,
      weight: 0,
      image: "touchdown-pop-squat.jpg",
      video_url: "https://www.youtube.com/embed/EjMVgmjOkZM?si=r7O5kcH7ZJerQBiU",
    },
    {
      id: 16,
      day_id: 4,
      name: "Mountain Climbers",
      sets: 4,
      reps: 12,
      weight: 0,
      image: "mountain-climbers.jpg",
      video_url: "https://www.youtube.com/embed/cnyTQDSE884?si=AWWxBgvTmutXTLJv",
    },
    {
      id: 17,
      day_id: 4,
      name: "Lateral Jump Squats",
      sets: 4,
      reps: 12,
      weight: 0,
      image: "lateral-jump-squats.jpg",
      video_url: "https://www.youtube.com/embed/--CHVAQ1_Kg?si=U28iwoGRb4oJpdEY",
    },

    // Day 5 (Full Body)
    {
      id: 18,
      day_id: 5,
      name: "Single Arm Shoulder Press with Static Split Squat",
      sets: 4,
      reps: 12,
      weight: 0,
      image: "single-arm-shoulder-press.jpg",
      video_url: "https://www.youtube.com/embed/FUwme_oBDsA?si=zhXQiEkl6x3AHgcy",
    },
    {
      id: 19,
      day_id: 5,
      name: "Dumbbell Good Mornings",
      sets: 4,
      reps: 12,
      weight: 0,
      image: "dumbbell-good-mornings.jpg",
      video_url: "https://www.youtube.com/embed/wUbsMNkkpLk?si=9Tsws0f6GwBbhpQ1",
    },
    {
      id: 20,
      day_id: 5,
      name: "Squat Bicep Curls",
      sets: 4,
      reps: 12,
      weight: 0,
      image: "squat-bicep-curls.jpg",
      video_url: "https://www.youtube.com/embed/Btoh_Jax7jA?si=V4_2mersreYSiv00",
    },
  ]);
}
